/* ============================================================
   App Router — Client-side SPA navigation (self-contained)
   ============================================================ */
const ROUTES = { '#/login': { page: 'login', auth: false }, '#/dashboard': { page: 'dashboard', auth: true }, '#/pedidos': { page: 'pedidos', auth: true }, '#/pedido': { page: 'pedido-detalhe', auth: true } };
const DEFAULT_ROUTE = '#/dashboard';
const LOGIN_ROUTE = '#/login';
let $app, chartInstance = null;

function init() {
  $app = document.getElementById('app');
  if (!$app) return;
  window.addEventListener('hashchange', handleRoute);
  handleRoute();
}
function handleRoute() {
  const hash = window.location.hash || DEFAULT_ROUTE;
  const route = resolveRoute(hash);
  if (!route) { navigateTo(DEFAULT_ROUTE); return; }
  if (route.auth && !auth.isAuthenticated()) { navigateTo(LOGIN_ROUTE); return; }
  if (!route.auth && auth.isAuthenticated() && hash !== LOGIN_ROUTE && hash.split('?')[0].split('/').slice(0,2).join('/') === '#/login') { navigateTo(DEFAULT_ROUTE); return; }
  renderPage(route, hash);
}
function resolveRoute(hash) {
  const base = hash.split('?')[0].split('/').slice(0,2).join('/');
  if (ROUTES[base]) return ROUTES[base];
  for (const [p, r] of Object.entries(ROUTES)) {
    if ((p.includes(':')||p.endsWith('/*')) && hash.startsWith(p.replace('/:id','').replace('/*',''))) return r;
  }
  return null;
}
function getLoginHTML() { return '<div class="login-card__logo"><h1>🎬 Memórias em Vídeo</h1><p>Painel administrativo</p></div><div id="login-alert"></div><form id="login-form" autocomplete="on" novalidate><div class="form-group"><label for="email">E-mail</label><input type="email" id="email" class="form-input" placeholder="seu@email.com" required autocomplete="email" inputmode="email"><div class="form-error hidden" id="email-error">Informe um e-mail válido</div></div><div class="form-group"><label for="password">Senha</label><input type="password" id="password" class="form-input" placeholder="Sua senha" required autocomplete="current-password" minlength="4"><div class="form-error hidden" id="password-error">A senha é obrigatória</div></div><button type="submit" id="login-btn" class="btn btn-primary btn-block btn-lg">Entrar</button></form><p class="login-card__footer">Ambiente seguro · TLS 1.3</p>'; }
function initLoginForm() {
  const form = document.getElementById('login-form'), btn = document.getElementById('login-btn'), alertEl = document.getElementById('login-alert');
  if (!form || !btn || !alertEl) return;
  form.addEventListener('submit', async e => {
    e.preventDefault(); alertEl.innerHTML = '';
    const email = document.getElementById('email').value.trim(), password = document.getElementById('password').value;
    const ee = document.getElementById('email-error'), pe = document.getElementById('password-error');
    if (ee) ee.classList.add('hidden'); if (pe) pe.classList.add('hidden');
    if (!email||!email.includes('@')) { if (ee) ee.classList.remove('hidden'); return; }
    if (!password||password.length<4) { if (pe) pe.classList.remove('hidden'); return; }
    btn.disabled = true; btn.innerHTML = '<span class="spinner-btn"></span> Entrando…';
    try { await auth.login(email,password); window.location.hash='#/dashboard'; }
    catch(err) { if (alertEl) alertEl.innerHTML='<div class="alert alert--error">'+escapeHtml(err.message||'Erro ao fazer login')+'</div>'; btn.disabled=false; btn.innerHTML='Entrar'; }
  });
}
function getDashboardHTML() { return '<div class="metrics-grid" id="metrics-grid"><div class="metric-card"><div class="metric-card__icon metric-card__icon--blue">📦</div><div class="metric-card__label">Pedidos Hoje</div><div class="metric-card__value" id="metric-hoje"><div class="skeleton skeleton--text-lg" style="width:60px"></div></div></div><div class="metric-card"><div class="metric-card__icon metric-card__icon--green">📊</div><div class="metric-card__label">Este Mês</div><div class="metric-card__value" id="metric-mes"><div class="skeleton skeleton--text-lg" style="width:60px"></div></div></div><div class="metric-card"><div class="metric-card__icon metric-card__icon--yellow">✅</div><div class="metric-card__label">Taxa de Aprovação</div><div class="metric-card__value" id="metric-taxa"><div class="skeleton skeleton--text-lg" style="width:80px"></div></div></div><div class="metric-card"><div class="metric-card__icon metric-card__icon--red">⏱️</div><div class="metric-card__label">Tempo Médio</div><div class="metric-card__value" id="metric-tempo"><div class="skeleton skeleton--text-lg" style="width:80px"></div></div></div></div><div class="cols-2"><div class="card"><div class="card__header"><h3>📈 Pedidos por Tipo de Evento</h3></div><div class="card__body"><div class="chart-container"><canvas id="chart-eventos"></canvas></div></div></div><div class="card"><div class="card__header"><h3>📋 Últimos Pedidos</h3><a href="#/pedidos" class="btn btn-sm btn-secondary">Ver todos</a></div><div class="card__body" style="padding:0;"><div class="table-wrapper"><table><thead><tr><th>Cliente</th><th>Evento</th><th>Status</th><th>Data</th></tr></thead><tbody id="ultimos-pedidos-tbody"><tr class="skeleton-row"><td><div class="skeleton skeleton--text" style="width:60%"></div></td><td><div class="skeleton skeleton--text" style="width:50%"></div></td><td><div class="skeleton skeleton--text-sm" style="width:40%"></div></td><td><div class="skeleton skeleton--text-sm" style="width:30%"></div></td></tr></tbody></table></div></div></div></div>'; }
function getPedidosHTML() { return '<div class="card"><div class="card__header"><h3>📋 Pedidos</h3><span id="pedidos-count" style="font-size:var(--font-size-sm);color:var(--color-ink-secondary);"></span></div><div class="card__body"><div class="filters-bar"><input type="text" class="form-input" id="filter-busca" placeholder="Buscar nome ou telefone…" oninput="debounceFilter()"><select class="form-input" id="filter-status" onchange="applyFilters()"><option value="">Todos os status</option><option value="pendente">Pendente</option><option value="aprovado">Aprovado</option><option value="processando">Processando</option><option value="concluido">Concluído</option><option value="cancelado">Cancelado</option><option value="erro">Erro</option></select><select class="form-input" id="filter-evento" onchange="applyFilters()"><option value="">Todos os eventos</option></select><input type="date" class="form-input" id="filter-data-inicio" onchange="applyFilters()" title="Data início"><input type="date" class="form-input" id="filter-data-fim" onchange="applyFilters()" title="Data fim"></div><div class="table-wrapper"><table><thead><tr><th>Cliente</th><th>Telefone</th><th>Evento</th><th>Status</th><th>Fotos</th><th>Data</th><th></th></tr></thead><tbody id="pedidos-tbody"><tr class="skeleton-row"><td><div class="skeleton skeleton--text" style="width:60%"></div></td><td><div class="skeleton skeleton--text-sm" style="width:45%"></div></td><td><div class="skeleton skeleton--text" style="width:50%"></div></td><td><div class="skeleton skeleton--text-sm" style="width:35%"></div></td><td><div class="skeleton skeleton--text-sm" style="width:20%"></div></td><td><div class="skeleton skeleton--text-sm" style="width:30%"></div></td><td><div class="skeleton skeleton--text-sm" style="width:25%"></div></td></tr></tbody></table></div><div class="pagination" id="pagination"><span id="pagination-info">Carregando…</span><div class="pagination__buttons" id="pagination-buttons"></div></div></div></div>'; }
function getPedidoDetalheHTML() { return '<div id="pedido-detail-loading" class="loading-overlay"><div class="spinner"></div><span>Carregando pedido…</span></div><div id="pedido-detail-content" class="hidden"><nav style="display:flex;align-items:center;gap:var(--space-3);margin-bottom:var(--space-6);flex-wrap:wrap;"><a href="#/pedidos" class="btn btn-sm btn-secondary">← Voltar</a><span id="detail-status" class="badge badge--info">Carregando…</span><span id="detail-id" style="font-size:var(--font-size-xs);color:var(--color-ink-muted);font-family:var(--font-mono);"></span></nav><div id="sse-status-bar" class="hidden alert alert--info" style="margin-bottom:var(--space-4);font-size:var(--font-size-xs);">🔄 Status atualizado em tempo real</div><div class="detail-grid"><div><div class="detail-section"><div class="detail-section__title">📸 Fotos Enviadas</div><div id="fotos-section"><div id="fotos-gallery" class="photo-gallery"></div><div id="fotos-empty" class="hidden"><div class="empty-state"><div class="empty-state__icon">🖼️</div><div class="empty-state__text">Nenhuma foto enviada</div></div></div></div></div><div class="detail-section"><div class="detail-section__title">🎯 Curadoria</div><div class="curation-tabs"><button class="curation-tab curation-tab--active" data-curation="all" onclick="filterCuration(\'all\')">Todas</button><button class="curation-tab" data-curation="selected" onclick="filterCuration(\'selected\')">Selecionadas</button><button class="curation-tab" data-curation="rejected" onclick="filterCuration(\'rejected\')">Rejeitadas</button></div><div id="curation-gallery" class="photo-gallery"></div></div></div><div><div class="detail-section"><div class="detail-section__title">👤 Cliente</div><div id="cliente-info"></div></div><div class="detail-section"><div class="detail-section__title">🎉 Evento</div><div id="evento-info"></div></div><div class="detail-section"><div class="detail-section__title">🎬 Vídeo</div><div id="video-section"><div id="video-empty" class="empty-state"><div class="empty-state__icon">🎥</div><div class="empty-state__text">Vídeo ainda não gerado</div><p>Após a curadoria e processamento, o vídeo aparecerá aqui.</p></div><div id="video-player-wrapper" class="hidden"><div class="video-player"><video id="video-player" controls preload="metadata"></video></div></div></div></div><div class="action-bar"><button class="btn btn-primary" onclick="reprocessarPedido()" id="btn-reprocessar">🔄 Reprocessar</button><button class="btn btn-danger" onclick="cancelarPedido()" id="btn-cancelar">🚫 Cancelar</button></div></div></div></div>'; }
function statusBadgeClass(s) { return ({'pendente':'warning','aprovado':'success','processando':'info','concluido':'success','concluído':'success','cancelado':'danger','rejeitado':'danger','erro':'danger'})[s?.toLowerCase()]||'neutral'; }
function statusLabelMap(s) { return ({'pendente':'Pendente','aprovado':'Aprovado','processando':'Processando','concluido':'Concluído','concluído':'Concluído','cancelado':'Cancelado','rejeitado':'Rejeitado','erro':'Erro'})[s?.toLowerCase()]||s||'—'; }
function esc(str) { if (!str) return '—'; const d=document.createElement('div'); d.textContent=str; return d.innerHTML; }
